### ISSUE TITLE
Live 9.5 64bit LED colors

### ISSUE THREAD

**Issue by philrossimusic** [mpiraux/CMD-LC-1-Ableton-9-Control-Surface-Script#2]
Hey! First off--thanks for pulling this together. Overall, a life saver. However, should my clip colors be (roughly) represented by the LEDs on the unit? FYI--I did not make a new directory for the LC1 only dropped in the new files from your repository into the directory I had created at initial set up.
Thanks!
Phil

**Comment by mpiraux** [comment]
From the few minutes I spent using the LC-1 with the original script from Behringer and Ableton 9.0, the colors on the LC did not match my clips at all. 
The color code is rather based on the state of the clip, blue for unplayed and green for playing.
Replacing the files is sufficient in most case, creating a new directory is mainly to avoid strange compiling errors that sometimes happens, which is not the case here.

My intent here is to maintain the original script, so I'm not going to add features to it in the near future.
Have fun with it anyway!

**Comment by philrossimusic** [comment]
That's what I thought. This is a great script you've put together. Thank you!

**Comment by philrossimusic** [comment]
Conceptually (high concept, not trying to make you do work) do you think additional color coding for clip launches would be possible? Even if it is just having each "lane" being a different color.

**Comment by mpiraux** [comment]
It's totally possible, but I fear mostly that the device would then lack of clearness regarding the state of the clip, because the device only haves 4 different colors.
I'm quite happy personally with the state of the colors for clip launches.
I might start a new script combining the DC-1 and the LC-1 into one more featured controller than those 2 are separately, but unfortunately I lack time until February.

**Comment by philrossimusic** [comment]
I agree. :)  This would be a "visual" aid to help (me at least) distinguish my clips in the grid. 

So--if i have this right:

AMBER
GREEN 
PINK 
BLUE

Are Cyan, Yellow, White, Violet, and red possible?  I would think that green could always be representative of a launched clip (or blinking green).  So, then that would leave at the very least Amber, Pink, and Blue--so you could repeat that pattern for reach row perhaps. 

Just thoughts. I wish I knew how to code in python! :)
