### ISSUE TITLE
Graphic map controllers

### ISSUE THREAD

**Issue by Playtagain** [mpiraux/CMD-LC-1-Ableton-9-Control-Surface-Script#4]
Hi, thanks for your work! My new LC1 is perfect in Live 9.5, but I do not know what function each button . I have also seen that the knobs are not assigned to any parameters . You can display a graph mapping scheme ? Thank you very much.

**Comment by mpiraux** [comment]
Hi!
Maybe you didn't figure out, but the script available here is only a port of the Behringer script. So the original mapping should remain the same. There is one PDF bundled with the Behringer script that displays the scheme, i'm joining it here for you: [CMD LC-1 ABLETON MAP (v1.0).pdf](https://github.com/mpiraux/CMD-LC-1-Ableton-9-Control-Surface-Script/files/165486/CMD.LC-1.ABLETON.MAP.v1.0.pdf)

If you find something that does not match the scheme, report it here so I can investigate on that ;)
Have fun!

**Comment by Playtagain** [comment]
Thank you, internet is great for people like you. I have a few days
fighting with LC1 , and I think I return . There is no way to make Traktor
recognize the knobs .... Or I do wrong, or this is very difficult for me
... Thanks.

2016-03-09 16:48 GMT+01:00 Maxime Piraux notifications@github.com:
